//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concierge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concierge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ability {
            get {
                object obj = ResourceManager.GetObject("Ability", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AboutBanner {
            get {
                object obj = ResourceManager.GetObject("AboutBanner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawful Good
        ///Neutral Good
        ///Chaotic Good
        ///Lawful Neutral
        ///True Neutral
        ///Chaotic Neutral
        ///Lawful Evil
        ///Neutral Evil
        ///Chaotic Evil.
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ammunition {
            get {
                object obj = ResourceManager.GetObject("Ammunition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///5
        ///10
        ///15
        ///20
        ///30
        ///45
        ///60
        ///90
        ///120.
        /// </summary>
        internal static string AutosaveInterval {
            get {
                return ResourceManager.GetString("AutosaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acolyte
        ///Anthropologist
        ///Archaeologist
        ///Caravan Specialist
        ///Charlatan
        ///City Watch
        ///Cloistered Scholar
        ///Courtier
        ///Criminal
        ///Dissenter
        ///Entertainer
        ///Folk Hero
        ///Gladiator
        ///Guild Artisan
        ///Guild Merchant
        ///Harborfolk
        ///Haunted One
        ///Hermit
        ///Inheritor
        ///Initiate
        ///Inquisitor
        ///Investigator
        ///Knight
        ///Noble
        ///Outlander
        ///Pirate
        ///Sage
        ///Sailor
        ///Soldier
        ///Urchin.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventuring Gear
        ///Arcane Focus
        ///Clothing
        ///Druidic Focus
        ///Equipment Pack
        ///Gemstone
        ///Heavy Armor
        ///Holy Symbol
        ///Light Armor
        ///Medium Armor
        ///Mount
        ///Poison
        ///Shield
        ///Tool
        ///Vehicle (Land)
        ///Vehicle (Water).
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artificer
        ///Barbarian
        ///Bard
        ///Blood Hunter
        ///Cleric
        ///Druid
        ///Fighter
        ///Monk
        ///Paladin
        ///Ranger
        ///Rogue
        ///Sorcerer
        ///Warlock
        ///Wizard.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bardic Inspiration
        ///Divine Sense
        ///Hemocraft Dice
        ///Infusions
        ///Ki Points
        ///Lay on Hands
        ///Rages
        ///Sneak Attack Dice
        ///Sorcery Points
        ///Superiority Dice.
        /// </summary>
        internal static string ClassResource {
            get {
                return ResourceManager.GetString("ClassResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ColorPickerBackground {
            get {
                object obj = ResourceManager.GetObject("ColorPickerBackground", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Set
        ///Dragonchess Set
        ///Playing Card Set
        ///Three-Dragon Ante Set.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GenericTapSoundLoud {
            get {
                return ResourceManager.GetStream("GenericTapSoundLoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GenericWarning {
            get {
                return ResourceManager.GetStream("GenericWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hey_whats_going_on {
            get {
                object obj = ResourceManager.GetObject("hey-whats-going-on", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream HighPitchTapSoundLoud {
            get {
                return ResourceManager.GetStream("HighPitchTapSoundLoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagpipes
        ///Drum
        ///Dulcimer
        ///Flute
        ///Horn
        ///Lute
        ///Lyre
        ///Pan Flute
        ///Shawm
        ///Viol.
        /// </summary>
        internal static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Inventory {
            get {
                object obj = ResourceManager.GetObject("Inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Language {
            get {
                object obj = ResourceManager.GetObject("Language", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300
        ///900
        ///2700
        ///6500
        ///14000
        ///23000
        ///34000
        ///48000
        ///64000
        ///85000
        ///100000
        ///120000
        ///140000
        ///165000
        ///195000
        ///225000
        ///265000
        ///305000
        ///355000
        ///0.
        /// </summary>
        internal static string LevelExp {
            get {
                return ResourceManager.GetString("LevelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///2
        ///2
        ///2
        ///3
        ///3
        ///3
        ///3
        ///4
        ///4
        ///4
        ///4
        ///5
        ///5
        ///5
        ///5
        ///6
        ///6
        ///6
        ///6.
        /// </summary>
        internal static string ProficiencyLevel {
            get {
                return ResourceManager.GetString("ProficiencyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aarakocra
        ///Aasimar
        ///Bugbear
        ///Dragonborn
        ///Dwarf
        ///Elf
        ///Genasi
        ///Gnome
        ///Goliath
        ///Half-Elf
        ///Half-Orc
        ///Halfling
        ///Human
        ///Kenku
        ///Tabaxi
        ///Tiefling
        ///Tortle
        ///Triton
        ///Warforged
        ///Yuan-ti-Pureblood.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ResourceValidation {
            get {
                return ResourceManager.GetString("ResourceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spell {
            get {
                object obj = ResourceManager.GetObject("Spell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid
        ///Bludgeoning
        ///Cold
        ///Fire
        ///Force
        ///Lightning
        ///Magic Weapons
        ///Necrotic
        ///Nonmagical
        ///Piercing
        ///Poison
        ///Psychic
        ///Radiant
        ///Slashing
        ///Spells
        ///Thunder.
        /// </summary>
        internal static string StatusEffect {
            get {
                return ResourceManager.GetString("StatusEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemist&apos;s Supplies
        ///Brewer&apos;s Supplies
        ///Calligrapher&apos;s Supplies
        ///Carpenter&apos;s Tools
        ///Cartographer&apos;s Tools
        ///Cobbler&apos;s Tools
        ///Disguise Kit
        ///Forgery Kit
        ///Glassblower&apos;s Tools
        ///Herbalism Kit
        ///Herbalism Kit
        ///Leatherworker&apos;s Tools
        ///Mason&apos;s Tools
        ///Navigator&apos;s Tools
        ///Painter&apos;s Supplies
        ///Poisoner&apos;s kit
        ///Potter&apos;s Tools
        ///Smith&apos;s Tools
        ///Thieves&apos; Tools
        ///Tinker&apos;s Tools
        ///Weaver&apos;s Tools
        ///Woodcarver&apos;s Tools.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Weapon {
            get {
                object obj = ResourceManager.GetObject("Weapon", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
